# Q1(1):
### 1. PMF of geometric distribution:
$$ P(X = k) = (1-p)^{k-1}p $$
It represents the probability that the first success occurs exactly on the k-th trial,where $k = 1, 2, 3, ...$ and $0 < p \leq 1$


### 2. CDF of geometric distribution:
$$ F(k) = P(X \leq k) = 1 - (1-p)^k $$


### 3. PPF of geometric distribution:
$$ \text{PPF}(q) = \min \{ k \in \mathbb{N}^+ \mid P(X \leq k) \geq q \} $$
where $0 < q < 1$


### 4. Expected Value:
$$ E[X] = \frac{1}{p} $$

### 5. Variance:
$$ Var(X) = \frac{1-p}{p^2} $$

(a): Calculate the probability P(K = 4)

In [1]:
import numpy as np
from scipy.stats import geom

# Set the success probability
p = 0.25

# Calculate P(K = 4) using PMF
p4 = geom.pmf(k=4, p=p)

print(f"a. P(K = 4) = {p4:.4f}")

a. P(K = 4) = 0.1055


(b): Calculate the probability P(K ≤ 3)

In [3]:
# Calculate P(K ≤ 3) using CDF
p3 = geom.cdf(k=3, p=p)

print(f"b. P(K ≤ 3) = {p3:.4f}")

b. P(K ≤ 3) = 0.5781


(c): Calculate the 0.7 quantile

In [2]:
# Calculate 0.7 quantile using PPF. The quantile is the smallest k where P(X ≤ k) ≥ 0.7
quantile_07 = geom.ppf(q=0.7, p=p)

print(f"c. The 0.7 quantile is: {int(quantile_07)}")
print(f"   This means P(X ≤ {int(quantile_07)}) ≥ 0.7")

c. The 0.7 quantile is: 5
   This means P(X ≤ 5) ≥ 0.7


(d): Generate n = 100 random samples from this distribution

In [4]:
np.random.seed(42)  # Set seed for reproducibility

# Generate 100 random samples from geometric distribution
samples = geom.rvs(p=p, size=100)

# Display samples
print("d. All 100 random samples:")
for i in range(0, 100, 10):
    print(samples[i:i + 10])

d. All 100 random samples:
[ 2 11  5  4  1  1  1  7  4  5]
[ 1 13  7  1  1  1  2  3  2  2]
[4 1 2 2 3 6 1 3 4 1]
[ 4  1  1 11 12  6  2  1  5  3]
[1 3 1 9 2 4 2 3 3 1]
[13  6 10  8  4  9  1  1  1  2]
[ 2  2  7  2  2  3  1  6  1 16]
[6 1 1 6 5 5 6 1 2 1]
[7 4 2 1 2 2 5 4 8 3]
[1 5 5 3 6 3 3 2 1 1]


# Q1(2): Chi-Squared Distribution (df = 4)
The chi-squared distribution is a **continuous probability distribution**, denoted as $\chi^2(\nu)$, where $\nu$ (pronounced "nu") represents the **degrees of freedom** — a positive integer parameter that defines the distribution's shape.

### 1. PDF
The PDF describes the relative likelihood of the random variable taking a specific value $x$:
$$ f(x; \nu) = \begin{cases}
    \frac{1}{2^{\nu/2} \Gamma(\nu/2)} x^{\nu/2 - 1} e^{-x/2} & \text{if } x > 0, \\ 0 & \text{if } x \leq 0
\end{cases} $$

### 2. CDF
The CDF gives the probability that the random variable $X$ is less than or equal to a value $x$:
$$ F(x; \nu) = P(X \leq x) = \frac{1}{2^{\nu/2} \Gamma(\nu/2)} \int_{0}^{x} t^{\nu/2 - 1} e^{-t/2} dt $$

### 3. PPF
The PPF is the inverse of the CDF, returning the smallest $x$ such that cumulative probability is at least $q$:
$$ \text{PPF}(q; \nu) = \min \{ x \geq 0 \mid F(x; \nu) \geq q \} $$

(a): Calculate the density function at x = 2

In [5]:
import numpy as np
from scipy.stats import chi2

df = 4  # Degrees of freedom
x_value = 2

# Calculate PDF at x = 2
pdf_value = chi2.pdf(x=x_value, df=df)

print(f"a. Density function at x = 2: {pdf_value:.4f}")

a. Density function at x = 2: 0.1839


(b): Calculate the probability P(X ≤ 3)

In [6]:
# Calculate CDF at x = 3
cdf_value = chi2.cdf(x=3, df=df)

print(f"b. P(X ≤ 3) = {cdf_value:.4f}")

b. P(X ≤ 3) = 0.4422


c: Find x such that P(X ≤ x) = 0.9

In [7]:
# Calculate PPF for 0.9 quantile
x_quantile = chi2.ppf(q=0.9, df=df)

print(f"c. x value where P(X ≤ x) = 0.9: {x_quantile:.4f}")

c. x value where P(X ≤ x) = 0.9: 7.7794


(d): Generate n = 100 random samples from this distribution

In [8]:
np.random.seed(42)  # Set seed for reproducibility
samples2 = chi2.rvs(df=df, size=100)

print("d. All 100 random samples:")
# Display 10 samples per line for readability
for i in range(0, 100, 10):
    print(samples2[i:i+10].round(4))  # Display with 4 decimal places

d. All 100 random samples:
[4.7874 2.9889 2.7646 2.7646 9.2994 5.7334 2.2622 4.9396 3.9979 0.4318]
[1.3425 4.2123 8.7304 2.7837 2.1161 3.628  2.0106 2.6355 3.2986 1.2803]
[5.9401 1.0704 0.9456 3.8679 5.6267 3.7957 3.0436 2.6148 2.2798 6.8756]
[4.2421 2.4346 1.8732 5.1752 6.7669 6.3624 1.6021 2.597  2.2429 2.8766]
[5.9022 8.2045 4.357  1.9297 3.2417 9.2251 3.5632 2.6194 2.7977 4.343 ]
[1.6513 2.1984 6.2995 4.2563 3.5903 6.512  1.8294 2.5569 4.1579 4.0538]
[ 0.8517  2.3609  2.934   4.4892  4.0435  3.1448  0.4282  3.2653  3.4913
 14.596 ]
[2.8609 4.1741 7.2404 5.6761 8.4256 0.8658 1.3741 2.0745 0.7186 3.5135]
[1.4784 9.1504 1.6924 2.569  5.9059 1.0583 0.6672 3.8331 4.0504 5.7869]
[ 4.8708  4.1604  1.8678  3.9697  4.1487  1.8082 10.8442  4.7125  1.3969
  5.8066]


### Q2 Steps for MLE derivations

$P(X=x) = \frac{e^{-\lambda} \lambda^x}{x!}$, $x = 0, 1, 2, \ldots$

$L(\lambda) = \prod_{i=1}^n \frac{e^{-\lambda} \lambda^{X_i}}{X_i!}$

$l(\lambda) = \ln L(\lambda) = \ln \left( \prod_{i=1}^n \frac{e^{-\lambda} \lambda^{X_i}}{X_i!} \right) = \sum_{i=1}^n [-\lambda + X_i \cdot \ln(\lambda) - \ln(X_i!)] = -n\lambda + \ln(\lambda) \cdot \sum X_i - \sum \ln(X_i!)$

$\frac{dl}{d\lambda} = -n + \frac{1}{\lambda} \cdot \sum X_i = 0$

$\hat{\lambda} = \frac{\sum X_i}{n} = \bar{X}$


In [ ]:
import numpy as np
from scipy.stats import poisson

# Set true parameter and random seed
true_lambda = 3
np.random.seed(5102)

# Generate 100 Poisson distribution samples
n = 100
samples = poisson.rvs(mu=true_lambda, size=n)

# Print the generated samples
print("Generated Poisson samples:")
for i in range(0, n, 10):
    print(samples[i:i+10])

# Use MLE to estimate λ
mle_estimate = np.mean(samples)

# Output results
print(f"λ_true: {true_lambda}")
print(f"λ_MLE: {mle_estimate:.4f}")
print(f"Bias: {abs(mle_estimate - true_lambda):.4f}")
print(f"Relative Error: {abs(mle_estimate - true_lambda)/true_lambda*100:.4f}%")


Generated Poisson samples:
[4 2 3 2 6 2 5 5 3 2]
[4 6 0 4 4 0 6 7 3 0]
[5 1 3 3 1 4 4 3 5 3]
[4 3 3 3 3 3 1 2 3 0]
[0 1 6 0 2 3 0 2 6 1]
[0 5 7 2 7 3 2 3 4 5]
[5 1 1 2 5 4 3 2 1 6]
[3 3 3 3 5 5 3 5 3 0]
[4 3 4 3 1 4 2 4 2 3]
[5 4 2 3 6 1 3 0 4 5]
λ_true: 3
λ_MLE: 3.1000
Bias: 0.1000
Relative Error: 3.3333%


Q3(a) The code shows below:

In [ ]:
from scipy.stats import norm, t, chi2, f

np.random.seed(5102)

n1, mu1, sigma1_sq = 50, 15, 10
n2, mu2, sigma2_sq = 30, 20, 10
data1 = norm.rvs(loc=mu1, scale=np.sqrt(sigma1_sq), size=n1)
data2 = norm.rvs(loc=mu2, scale=np.sqrt(sigma2_sq), size=n2)

x1_bar = np.mean(data1)  # data1 mean
x2_bar = np.mean(data2)  # data2 mean
s1_sq = np.var(data1, ddof=1)  # data1 var unbiased
s2_sq = np.var(data2, ddof=1)  # data2 var unbiased
print(data1[:50])
print(data2[:30])

[19.03279277  8.93233502 17.75615606 16.06791378 15.55013996 13.02826755
 13.03370052 12.54012923 15.01666745 11.51442865 14.82258273 15.77402198
 16.10105655 12.45257174 17.92638049 11.85434412 16.7416956  14.40607808
  9.21526676 11.6082878  13.79486831 11.84954475 16.16217348 17.10037
 20.53811115 12.33342689 16.12804053 17.53038986 18.30376487 11.81604991
 14.50626832 15.92153643 15.52244643 19.1045124  11.78351849 14.12739097
 17.29850785 16.36926758 17.13092775 13.34793569 13.09926583 14.69601494
 13.9130117  16.11928222 15.29402644 17.70874024 16.49285199 17.56543801
 15.60276081 16.94357336]
[16.57440293 15.28028957 20.27543931 18.95141562 25.46317848 15.4164306
 16.04809873 25.6136073  14.64747499 23.23024311 20.37568918 23.33514293
 24.09645351 21.15714382 19.09289425 20.94030699 20.6963712  19.37758897
 16.00929827 23.7363922  22.55854595 23.92560686 22.28164683 15.63378998
 12.9413721  23.96338422 23.67294631 11.73283064 17.47270584 16.12858235]


Q3(b)
Because we already know the data variance and we have enough sample size, the Normal distribution is what we need: $$\bar{X}_1 \pm z_{\alpha/2}\cdot\frac{\sigma_1}{\sqrt{n_1}}$$ in which the $\alpha=0.01, \sigma_1=\sqrt{10}$, the code shows below.

In [ ]:
alpha = 0.01
z = norm.ppf(1 - alpha/2)
margin_error = z * np.sqrt(sigma1_sq) / np.sqrt(n1)
ci_b = (float(x1_bar - margin_error), float(x1_bar + margin_error))
print(" the confidence interval of μ1 at 99% confidence level: ", ci_b)

 the confidence interval of μ1 at 99% confidence level:  (13.877630795682743, 16.181522564151255)


Q3(c) We don't know the data variance this time so we use sample variance in stead, the t-distribution is what we need: $$\bar{X}_1 \pm t_{\alpha/2}(n_1-1)\cdot\frac{S_1}{\sqrt{n_1}}$$ in which the $\alpha=0.01$, $S_1$ stands for sample standard deviation, the code shows below.

In [ ]:
t_val = t.ppf(1 - alpha/2, df=n1-1)
margin_error_t = t_val * np.sqrt(s1_sq) / np.sqrt(n1)
ci_c = (float(x1_bar - margin_error_t), float(x1_bar + margin_error_t))
print(" the confidence interval of μ1 at the 99% confidence level：", ci_c)

 the confidence interval of μ1 at the 99% confidence level： (14.065453622337854, 15.993699737496145)


Q3(d) Because $\sigma_1^2=\sigma_2^2=10$, which means we know the pooled variance, then we use the Two-sample normal interval: $$(\bar{X}_1 - \bar{X}_2)\pm z_{\alpha/2}\cdot\sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}}$$ in which the $\alpha=0.01, \sigma_1=\sigma_2=\sqrt{10}$, the code shows below.

In [ ]:
alpha_d = 0.05
z_d = norm.ppf(1 - alpha_d/2)
se_d = np.sqrt(sigma1_sq/n1 + sigma2_sq/n2)
margin_error_d = z_d * se_d
ci_d = (float(x1_bar - x2_bar - margin_error_d), float(x1_bar - x2_bar + margin_error_d))
print(" the confidence interval of difference between μ1 and μ2 at the 95% confidence level：", ci_d)

 the confidence interval of difference between μ1 and μ2 at the 95% confidence level： (-6.0894210693426025, -3.226710439395152)


Q3(e) We know that $\sigma_1^2=\sigma_2^2$, but we don't know the pooled variance, then we use the Two-sample pooled variance t-distribution: $$(\bar{X}_1 - \bar{X}_2)\pm z_{\alpha/2}(n_1+n_2-2)\cdot\sqrt{S_p^2(\frac{1}{n_1}+\frac{1}{n_2})}$$ in which the $\alpha=0.01$, the code shows below.

In [ ]:
alpha_e = 0.01

sp_sq = ((n1-1)*s1_sq + (n2-1)*s2_sq) / (n1 + n2 - 2)
t_e = t.ppf(1 - alpha_e/2, df=n1+n2-2)
se_e = np.sqrt(sp_sq * (1/n1 + 1/n2))
margin_error_e = t_e * se_e
ci_e = (float(x1_bar - x2_bar - margin_error_e), float(x1_bar - x2_bar + margin_error_e))
print("he confidence interval of difference between μ1 and μ2 at the 99% confidence level：", ci_e)

he confidence interval of difference between μ1 and μ2 at the 99% confidence level： (-6.565462292304949, -2.7506692164328053)


Q3(f) We already know the data mean as $\mu_1=15$, then we can use Chi-square distribution:$$(\frac{\sum_{i=1}^{n_1}(X_{1i}-\mu_1)^2}{\chi_{\alpha/2}^2(n_1)},\frac{\sum_{i=1}^{n_1}(X_{1i}-\mu_1)^2}{\chi_{1-\alpha/2}^2(n_1)})$$ in which the $\sum_{i=1}^{n_1}(X_{1i}-\mu_1)^2$ means the sum of squared deviations from the mean we know, and the code shows below.

In [ ]:
alpha_f = 0.05
mu1_known = 15
sum_sq_f = np.sum((data1 - mu1_known)**2)
chi2_upper = chi2.ppf(1 - alpha_f/2, df=n1)
chi2_lower = chi2.ppf(alpha_f/2, df=n1)
ci_f = (float(sum_sq_f / chi2_upper), float(sum_sq_f / chi2_lower))
print(" the confidence interval of σ1² at the 95% confidence level：", ci_f)

 the confidence interval of σ1² at the 95% confidence level： (74.86266813008828, 165.2392457060951)


Q3(g) We don't know the data mean and variance, so we use the sample mean and variance instead, then we can use Chi-square distribution:$$(\frac{(n_1-1)S_1^2}{\chi_{\alpha/2}^2(n_1-1)},\frac{(n_1-1)S_1^2}{\chi_{1-\alpha/2}^2(n_1-1)})$$ in which the $S_1^2$ means the sample variance, and the code shows below.

In [ ]:
alpha_g = 0.05
chi2_upper_g = chi2.ppf(1 - alpha_g/2, df=n1-1)  # 70.222
chi2_lower_g = chi2.ppf(alpha_g/2, df=n1-1)      # 31.555
ci_g = (float((n1-1)*s1_sq / chi2_upper_g), float((n1-1)*s1_sq / chi2_lower_g))
print(" the confidence interval of σ1² at the 95% confidence level：", ci_g)

 the confidence interval of σ1² at the 95% confidence level： (4.515452190940315, 10.04870196905197)
