Q1(1)(d）

In [ ]:
import numpy as np

p = 0.2
sample_size = 100

np.random.seed(42)

print("geometric distribution with (p = 0.2)")
print("=" * 40)

samples = np.random.geometric(p, sample_size)
print(f"{samples[:100]}")

geometric distribution with (p = 0.2)
[ 3 14  6  5  1  1  1 10  5  6  1 16  9  2  1  1  2  4  3  2  5  1  2  3
  3  7  1  4  5  1  5  1  1 14 16  8  2  1  6  3  1  4  1 11  2  5  2  4
  4  1 16  7 13 11  5 12  1  1  1  2  3  2  8  2  2  4  1  8  1 20  7  1
  1  8  6  6  7  1  2  1  9  5  2  1  2  2  6  5 10  3  1  6  7  4  7  4
  4  3  1  1]


Q1(2)(c)

In [ ]:
from scipy.stats import chi2

x_chi2 = chi2.ppf(0.9, df=4)
print("x =", x_chi2)

x = 7.779440339734858


Q1(2)(d）

In [ ]:
np.random.seed(5102)
samples_chi2 = chi2.rvs(df=4, size=100)
print("samples:", samples_chi2[:100])

samples: [ 7.82932614  0.42821481  3.80299977  1.96869378  3.34696078  1.22048759
  4.31558593  1.65599799  4.96724188  2.8715342   2.44299451  1.36595221
 10.20808973  1.59572284  6.82393239  1.35091952  3.77836448  7.93325463
  5.58429967  4.58098662  2.00978342  3.09124006  3.57921447  6.07022357
  4.70685227  5.89740511  1.24572192  0.77399007 10.07960889  0.81674753
  0.59474425  6.72760435  7.92153094  4.37021404  3.93485962  2.85052573
  1.02133634  7.40943857  5.56490296  0.88822972  7.72961472  7.32155577
  0.11441488  3.89530473  3.02175366  2.3769275   3.79258824 15.36848591
  5.99002648  5.60670415  5.17065564  4.57852094  1.42046712 10.52331528
  9.31659486  1.30634633  2.13314326  0.8889963   3.24985424  1.21260131
  4.00096282  1.06710357  2.72513169  1.49216725  7.74585571  1.10769318
  2.25326193  1.42668381  1.0964435   3.89155882  1.24240903  5.36351505
  4.29402057  8.98406073  2.78027732  6.00942924  0.11109343  7.30278114
  4.28774855  1.19023196  2.16520154  4.86

Q2
Steps for MLE derivations

$P(X=x) = \frac{e^{-\lambda} \lambda^x}{x!}$, $x = 0, 1, 2, \ldots$

$L(\lambda) = \prod_{i=1}^n \frac{e^{-\lambda} \lambda^{X_i}}{X_i!}$

$l(\lambda) = \ln L(\lambda) = \ln \left( \prod_{i=1}^n \frac{e^{-\lambda} \lambda^{X_i}}{X_i!} \right) = \sum_{i=1}^n [-\lambda + X_i \cdot \ln(\lambda) - \ln(X_i!)] = -n\lambda + \ln(\lambda) \cdot \sum X_i - \sum \ln(X_i!)$

$\frac{dl}{d\lambda} = -n + \frac{1}{\lambda} \cdot \sum X_i = 0$

$\hat{\lambda} = \frac{\sum X_i}{n} = \bar{X}$


In [1]:
import numpy as np
from scipy.stats import poisson

# Set true parameter and random seed
true_lambda = 3
np.random.seed(5102)

# Generate 100 Poisson distribution samples
n = 100
samples = poisson.rvs(mu=true_lambda, size=n)

# Print the generated samples
print("Generated Poisson samples:")
for i in range(0, n, 10):
    print(samples[i:i+10])

# Use MLE to estimate λ
mle_estimate = np.mean(samples)

# Output results
print(f"λ_true: {true_lambda}")
print(f"λ_MLE: {mle_estimate:.4f}")
print(f"Bias: {abs(mle_estimate - true_lambda):.4f}")
print(f"Relative Error: {abs(mle_estimate - true_lambda)/true_lambda*100:.4f}%")


Generated Poisson samples:
[4 2 3 2 6 2 5 5 3 2]
[4 6 0 4 4 0 6 7 3 0]
[5 1 3 3 1 4 4 3 5 3]
[4 3 3 3 3 3 1 2 3 0]
[0 1 6 0 2 3 0 2 6 1]
[0 5 7 2 7 3 2 3 4 5]
[5 1 1 2 5 4 3 2 1 6]
[3 3 3 3 5 5 3 5 3 0]
[4 3 4 3 1 4 2 4 2 3]
[5 4 2 3 6 1 3 0 4 5]
λ_true: 3
λ_MLE: 3.1000
Bias: 0.1000
Relative Error: 3.3333%


Q3(a) The code shows below:

In [ ]:
from scipy.stats import norm, t, chi2, f

np.random.seed(5102)

n1, mu1, sigma1_sq = 50, 15, 10
n2, mu2, sigma2_sq = 30, 20, 10
data1 = norm.rvs(loc=mu1, scale=np.sqrt(sigma1_sq), size=n1)
data2 = norm.rvs(loc=mu2, scale=np.sqrt(sigma2_sq), size=n2)

x1_bar = np.mean(data1)  # data1 mean
x2_bar = np.mean(data2)  # data2 mean
s1_sq = np.var(data1, ddof=1)  # data1 var unbiased
s2_sq = np.var(data2, ddof=1)  # data2 var unbiased
print(data1[:50])
print(data2[:30])

[19.03279277  8.93233502 17.75615606 16.06791378 15.55013996 13.02826755
 13.03370052 12.54012923 15.01666745 11.51442865 14.82258273 15.77402198
 16.10105655 12.45257174 17.92638049 11.85434412 16.7416956  14.40607808
  9.21526676 11.6082878  13.79486831 11.84954475 16.16217348 17.10037
 20.53811115 12.33342689 16.12804053 17.53038986 18.30376487 11.81604991
 14.50626832 15.92153643 15.52244643 19.1045124  11.78351849 14.12739097
 17.29850785 16.36926758 17.13092775 13.34793569 13.09926583 14.69601494
 13.9130117  16.11928222 15.29402644 17.70874024 16.49285199 17.56543801
 15.60276081 16.94357336]
[16.57440293 15.28028957 20.27543931 18.95141562 25.46317848 15.4164306
 16.04809873 25.6136073  14.64747499 23.23024311 20.37568918 23.33514293
 24.09645351 21.15714382 19.09289425 20.94030699 20.6963712  19.37758897
 16.00929827 23.7363922  22.55854595 23.92560686 22.28164683 15.63378998
 12.9413721  23.96338422 23.67294631 11.73283064 17.47270584 16.12858235]


Q3(b)
Because we already know the data variance and we have enough sample size, the Normal distribution is what we need: $$\bar{X}_1 \pm z_{\alpha/2}\cdot\frac{\sigma_1}{\sqrt{n_1}}$$ in which the $\alpha=0.01, \sigma_1=\sqrt{10}$, the code shows below.

In [ ]:
alpha = 0.01
z = norm.ppf(1 - alpha/2)
margin_error = z * np.sqrt(sigma1_sq) / np.sqrt(n1)
ci_b = (float(x1_bar - margin_error), float(x1_bar + margin_error))
print(" the confidence interval of μ1 at 99% confidence level: ", ci_b)

 the confidence interval of μ1 at 99% confidence level:  (13.877630795682743, 16.181522564151255)


Q3(c) We don't know the data variance this time so we use sample variance in stead, the t-distribution is what we need: $$\bar{X}_1 \pm t_{\alpha/2}(n_1-1)\cdot\frac{S_1}{\sqrt{n_1}}$$ in which the $\alpha=0.01$, $S_1$ stands for sample standard deviation, the code shows below.

In [ ]:
t_val = t.ppf(1 - alpha/2, df=n1-1)
margin_error_t = t_val * np.sqrt(s1_sq) / np.sqrt(n1)
ci_c = (float(x1_bar - margin_error_t), float(x1_bar + margin_error_t))
print(" the confidence interval of μ1 at the 99% confidence level：", ci_c)

 the confidence interval of μ1 at the 99% confidence level： (14.065453622337854, 15.993699737496145)


Q3(d) Because $\sigma_1^2=\sigma_2^2=10$, which means we know the pooled variance, then we use the Two-sample normal interval: $$(\bar{X}_1 - \bar{X}_2)\pm z_{\alpha/2}\cdot\sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}}$$ in which the $\alpha=0.01, \sigma_1=\sigma_2=\sqrt{10}$, the code shows below.

In [ ]:
alpha_d = 0.05
z_d = norm.ppf(1 - alpha_d/2)
se_d = np.sqrt(sigma1_sq/n1 + sigma2_sq/n2)
margin_error_d = z_d * se_d
ci_d = (float(x1_bar - x2_bar - margin_error_d), float(x1_bar - x2_bar + margin_error_d))
print(" the confidence interval of difference between μ1 and μ2 at the 95% confidence level：", ci_d)

 the confidence interval of difference between μ1 and μ2 at the 95% confidence level： (-6.0894210693426025, -3.226710439395152)


Q3(e) We know that $\sigma_1^2=\sigma_2^2$, but we don't know the pooled variance, then we use the Two-sample pooled variance t-distribution: $$(\bar{X}_1 - \bar{X}_2)\pm z_{\alpha/2}(n_1+n_2-2)\cdot\sqrt{S_p^2(\frac{1}{n_1}+\frac{1}{n_2})}$$ in which the $\alpha=0.01$, the code shows below.

In [ ]:
alpha_e = 0.01

sp_sq = ((n1-1)*s1_sq + (n2-1)*s2_sq) / (n1 + n2 - 2)
t_e = t.ppf(1 - alpha_e/2, df=n1+n2-2)
se_e = np.sqrt(sp_sq * (1/n1 + 1/n2))
margin_error_e = t_e * se_e
ci_e = (float(x1_bar - x2_bar - margin_error_e), float(x1_bar - x2_bar + margin_error_e))
print("he confidence interval of difference between μ1 and μ2 at the 99% confidence level：", ci_e)

he confidence interval of difference between μ1 and μ2 at the 99% confidence level： (-6.565462292304949, -2.7506692164328053)


Q3(f) We already know the data mean as $\mu_1=5$, then we can use Chi-square distribution:$$(\frac{\sum_{i=1}^{n_1}(X_{1i}-\mu_1)^2}{\chi_{\alpha/2}^2(n_1)},\frac{\sum_{i=1}^{n_1}(X_{1i}-\mu_1)^2}{\chi_{1-\alpha/2}^2(n_1)})$$ in which the $\sum_{i=1}^{n_1}(X_{1i}-\mu_1)^2$ means the sum of squared deviations from the mean we know, and the code shows below.

In [ ]:
alpha_f = 0.05
mu1_known = 5
sum_sq_f = np.sum((data1 - mu1_known)**2)
chi2_upper = chi2.ppf(1 - alpha_f/2, df=n1)
chi2_lower = chi2.ppf(alpha_f/2, df=n1)
ci_f = (float(sum_sq_f / chi2_upper), float(sum_sq_f / chi2_lower))
print(" the confidence interval of σ1² at the 95% confidence level：", ci_f)

 the confidence interval of σ1² at the 95% confidence level： (74.86266813008828, 165.2392457060951)


Q3(g) We don't know the data mean and variance, so we use the sample mean and variance instead, then we can use Chi-square distribution:$$(\frac{(n_1-1)S_1^2}{\chi_{\alpha/2}^2(n_1-1)},\frac{(n_1-1)S_1^2}{\chi_{1-\alpha/2}^2(n_1-1)})$$ in which the $S_1^2$ means the sample variance, and the code shows below.

In [ ]:
alpha_g = 0.05
chi2_upper_g = chi2.ppf(1 - alpha_g/2, df=n1-1)  # 70.222
chi2_lower_g = chi2.ppf(alpha_g/2, df=n1-1)      # 31.555
ci_g = (float((n1-1)*s1_sq / chi2_upper_g), float((n1-1)*s1_sq / chi2_lower_g))
print(" the confidence interval of σ1² at the 95% confidence level：", ci_g)

 the confidence interval of σ1² at the 95% confidence level： (4.515452190940315, 10.04870196905197)
